language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vj/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-1-843069076802"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY